### ISSUE TITLE
paginate function is working well?

### ISSUE THREAD

**Issue by nguyentranchung** [lorisleiva/javel#5]
I follow the docs and write
```js
const users = await User.paginate({ data: { page: 2 } })
```
but my xhr request is:
```
http://localhost/api/v1/user
```

**Comment by nguyentranchung** [comment]
my Model.js
```js
import { Model as BaseModel } from 'javel'
import axios from 'axios'

export default class Model extends BaseModel {
  baseUrl () {
    return '/api/v1'
  }

  makeRequest ({ method, url, data, query }) {
    return axios({ method, url, data, params: query })
  }
}
```
User.js file
```js
import Model from './Model'

export default class User extends Model {
}
```
What am I wrong?

**Comment by lorisleiva** [comment]
Hi there 👋 

You're right this is a typo in the documentation.

You should be able to achieve this using `query` instead of `data` to add the `page=2` in your query string.

```js
const users = await User.paginate({ query: { page: 2 } })
```

Please let me know if everything works for you after this change and I'll update the documentation.

Thank you for reporting this! 👍

**Comment by nguyentranchung** [comment]
Thanks you for reply. I fixed that.
